2022-11-03 15:16:10.821 | ERROR    | nonebot:load_plugin:161 - Failed to import "星际旅行"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\星际旅行\__init__.py", line 28, in <module>
    @app.on.state("地球", "月亮", "太阳")
TypeError: state() takes from 1 to 2 positional arguments but 4 were given
2022-11-04 16:04:37.946 | ERROR    | nonebot:load_plugin:165 - Failed to import "星际旅行"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\星际旅行\__init__.py", line 1, in <module>
    from ayaka import AyakaApp
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka\__init__.py", line 3, in <module>
    from .storage import AyakaPath
ImportError: cannot import name 'AyakaPath' from 'ayaka.storage' (F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka\storage.py)
2022-11-04 16:04:38.128 | ERROR    | nonebot:load_plugin:165 - Failed to import "core"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka_test\core.py", line 9, in <module>
    from ayaka import logger
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka\__init__.py", line 3, in <module>
    from .storage import AyakaPath
ImportError: cannot import name 'AyakaPath' from 'ayaka.storage' (F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka\storage.py)
2022-11-04 16:04:38.293 | ERROR    | nonebot:load_plugin:165 - Failed to import "terminal"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka_test\terminal.py", line 6, in <module>
    from .core import fake_qq, divide
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka_test\core.py", line 9, in <module>
    from ayaka import logger
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka\__init__.py", line 3, in <module>
    from .storage import AyakaPath
ImportError: cannot import name 'AyakaPath' from 'ayaka.storage' (F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka\storage.py)
2022-11-04 16:04:38.472 | ERROR    | nonebot:load_plugin:165 - Failed to import "cqhttp"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka_test\cqhttp.py", line 2, in <module>
    from .core import fake_qq, bot_id
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka_test\core.py", line 9, in <module>
    from ayaka import logger
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka\__init__.py", line 3, in <module>
    from .storage import AyakaPath
ImportError: cannot import name 'AyakaPath' from 'ayaka.storage' (F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka\storage.py)
2022-11-04 16:07:43.298 | ERROR    | plugins:<module>:28 - 导入失败 cy_query
Traceback (most recent call last):
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\ayaka_games\__init__.py", line 25, in <module>
    import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\ayaka_games\plugins\cy_query\__init__.py", line 10, in <module>
    search_dict: dict = app.storage.plugin().jsonfile("data", {}).load()
AttributeError: 'AyakaDir' object has no attribute 'jsonfile'
2022-11-04 16:07:43.752 | ERROR    | plugins:<module>:28 - 导入失败 dragon
Traceback (most recent call last):
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\ayaka_games\__init__.py", line 25, in <module>
    import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\ayaka_games\plugins\dragon\__init__.py", line 145, in <module>
    for p in app.storage.plugin("词库").iterdir():
AttributeError: 'AyakaDir' object has no attribute 'iterdir'
2022-11-04 16:08:00.263 | ERROR    | plugins:<module>:28 - 导入失败 cy_query
Traceback (most recent call last):
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\ayaka_games\__init__.py", line 25, in <module>
    import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\ayaka_games\plugins\cy_query\__init__.py", line 10, in <module>
    search_dict: dict = app.storage.plugin().jsonfile("data", {}).load()
AttributeError: 'AyakaDir' object has no attribute 'jsonfile'
2022-11-04 16:08:00.613 | ERROR    | plugins:<module>:28 - 导入失败 dragon
Traceback (most recent call last):
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\ayaka_games\__init__.py", line 25, in <module>
    import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\ayaka_games\plugins\dragon\__init__.py", line 146, in <module>
    dragons.append(Dragon(p.stem))
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\ayaka_games\plugins\dragon\__init__.py", line 70, in __init__
    self._use = app.storage.plugin().jsonfile("use", {}).load().get(name, True)
AttributeError: 'AyakaDir' object has no attribute 'jsonfile'
2022-11-04 17:21:37.219 | ERROR    | plugins:<module>:28 - 导入失败 dragon
Traceback (most recent call last):
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\ayaka_games\__init__.py", line 25, in <module>
    import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\plugins\ayaka_games\plugins\dragon\__init__.py", line 60, in <module>
    file_dragon_manager = app.storage.group().json("dragon", {})
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka\storage.py", line 159, in group
    self.app.bot_id,
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka\ayaka.py", line 170, in bot_id
    return self.group.bot_id
  File "F:\code_project\robot\ayaka\nonebot_plugin_ayaka\ayaka\ayaka.py", line 180, in group
    return _group.get()
LookupError: <ContextVar name='_group' at 0x000001FC646D0C20>
